CREATE OR REPLACE VIEW config_model.fe_view
AS SELECT co.correlation_id AS execution_id,
    ap.name AS app_name,
    oh.id AS orchestration_id,
    oh.name AS orchestration_name,
    co.begin_timestamp AS begin_orchestration,
    co.end_timestamp AS end_orchestration,
    co.status AS orchestration_exec_status,
    pt.name AS step_type,
    os.orch_step AS step_id,
    os.name AS step_name,
    cos2.begin_timestamp AS begin_step,
    cos2.end_timestamp AS end_step,
    cos2.status AS step_exec_status,
    os.parallel_ind AS step_parallel_ind,
    efc.filename AS file_name,
    efc.file_entity AS entity,
    efc.file_date,
    efc.file_seq AS file_sequence,
    efc.file_size,
    efc.file_num_lines AS numb_lines,
    efc.lines_processed AS processed_lines,
    efc.lines_discarded AS discarded_lines,
    efc.lines_errors AS error_lines,
    ft.name AS direction
   FROM config_model.orch_head oh,
    config_model.orch_steps os,
    config_model.connections c,
    config_model.applications ap,
    config_model.application_versions av,
    config_model.protocol_type pt,
    config_model.data_domain_app_versions ddav,
    config_model.flow_type ft,
    config_model.ctrl_orch co,
    config_model.ctrl_orch_step cos2,
    config_model.exec_file_control efc
  WHERE 1 = 1 AND oh.id = os.orch_id AND oh.id = co.orch_id AND co.orch_id = cos2.orch_id AND cos2.orch_step_id = os.orch_step AND co.correlation_id::text = cos2.correlation_id::text AND cos2.correlation_id::text = efc.correlation_id::text AND os.connection_id IS NULL AND c.app_id = ap.id AND c.protocol_type_id = pt.id AND os.data_domain_app_version_id = ddav.id AND ddav.app_version_id = av.app_id AND av.app_id = ap.id AND ddav.flow_type_id = ft.id
  ORDER BY os.orch_step;